Replace call to `print` with call to `warn`
std.debug.print does not exist:

    ./foo.zig:4:14: error: container 'std.debug' has no member called 'print'
        std.debug.print("Hello, world!\n", .{});